name: Bump image tag

on:
  push:
    branches: main

jobs:
  build:
    name: Bump image tag
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        uses: actions/checkout@v2
        
      - name: Bump image tag
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          chmod +x ./.github/script.sh && ./.github/script.sh
