name: Bump image tag

on:
  push:
    branches: staging

jobs:
  build:
    name: Bump image tag
    runs-on: ubuntu-latest

    steps:
      - name: Check out
        if: github.event.pull_request.merged
        uses: actions/checkout@v2
        
      - name: Bump image tag
        if: github.event.pull_request.merged
        env:
          PAT: ${{ secrets.PAT }}
        run: |
          chmod +x ./.github/script.sh && ./.github/script.sh
