name: Bump image tag

on:
  push:
    branches: main

jobs:
  build:
    name: Bump image tag
    runs-on: ubuntu-latest

    steps:
      - name: Bump image tag
        env:
          PAT: ${{ secrets.PAT }}
        run: |
	  ./github/script.sh
